pose_collector:
  clock: 100
virtual_drone_clock: 100
field_cbf: [[0, 3.5], [0, 4.5]] # 衝突回避で避けられるよう、psiよりも一回り大きくとる
central_clock: 20
agents:
  agent_manager_clock: 20
  u_max: 0.1
  camera_sensor_rad: 1.0471975511965976 #画角 insta360 プロ動画リニア:短辺76.3deg
  kp_z: 0.1
  ref_z: 1
  kp_yaw: 1
  ref_yaw: 0
  unom_max: 0.1
trees:
  xy: [[1.75, 2.5]]
  avoid_radius: [1]
  no_phi_radius: [1]
  show_radius: [0.1]

