detect_filter:
  decide_count: 3
  object_span: 0.5
  same_object_error: 0.2
dummy_object_detector:
  positions: [[1, 1, 1.5], [2.5, 2.5, 1.5], [1, 3, 1.5], [3, 1, 1.5]]
  detect_radius: 0.7 ### = height * tan(math.pi/2 - range[3][0])
  clock : 3
pictogram:
  size: 0.5
  character: fa-apple-alt
  z_offset : 0
  rotate_speed : 0.1