detect_filter:
  decide_count: 3
  object_span: 0.5
  same_object_error: 0.2
dummy_object_detector:
  positions: [[2.25, 0.75, 1.7], [2.6, 4, 1.7]]
  detect_radius: 0.7 ### = height * tan(math.pi/2 - range[3][0])
  clock : 3
pictogram:
  size: 0.5
  character: fa-apple-alt
  z_offset : 0
  rotate_speed : 0.1