angle_aware:
  sigma: 0.2
  delta_decrease: 5
  gamma: 0.1
  alpha: 1
  psi:
    range: [[-1.1, 1.1], [-1.1, 0]]
    density: [0.01, 0.01]
    npy_name: patrol_psi_sky_agri.npy
  slack_cost: 1000000
  unom_max: 0.1

output_psi_topic: patrol_psi
output_J_topic: patrol_J