angle_aware:
  sigma: 0.2
  delta_decrease: 5
  gamma: 0.1
  alpha: 1
  psi:
    range: [[-1.1, 1.1], [-1.1, 1.1]]
    density: [0.05, 0.05]
    npy_name: patrol_psi_sky.npy
output_psi_topic: patrol_psi
output_J_topic: patrol_J