angle_aware:
  sigma: 0.2
  delta_decrease: 5
  gamma: 0.1
  alpha: 1
  psi:
    range: [[0.3, 3.2], [0.3, 5]]
    density: [0.01, 0.01]
    npy_name: patrol_psi_orchard.npy
  slack_cost: 1000000
output_psi_topic: patrol_psi
output_J_topic: patrol_J