angle_aware:
  sigma: 0.3
  delta_decrease: 5
  gamma: 0.1
  alpha: 1
  psi:
    range: [[0.3, 3.2], [0.3, 3.7]]
    density: [0.05, 0.05]
    npy_name: patrol_psi_hijikata.npy
output_psi_topic: patrol_psi
output_J_topic: patrol_J