pose_collector:
  clock: 100
virtual_drone_clock: 100
field_cbf: [[-1.3, 1.3], [-1.3, 1.3]] # 衝突回避で避けられるよう、psiよりも一回り大きくとる
central_clock: 20
agents:
  agent_manager_clock: 20
  u_max: 0.3
  camera_sensor_rad: 0.7895822394
  kp_z: 0.3
  ref_z: 1.5
  kp_yaw: 1
  ref_yaw: 0
  unom_max: 0.1
trees:
  xy: [[0, 0]]
  avoid_radius: [0.1]
  no_phi_radius: [0.2]
  show_radius: [0.1]
